name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-live script
        run: echo Hellow, world!

      - name: Run a multi-line script
        run:
          echo Add other actions to build,
          echo test, and deploy your project.
          echo Additional line.